
package com.mao.webs.main;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MyFirstWebServiceService", targetNamespace = "http://main.webs.mao.com/", wsdlLocation = "http://localhost:4567/one?wsdl")
public class MyFirstWebServiceService
    extends Service
{

    private final static URL MYFIRSTWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.mao.webs.main.MyFirstWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.mao.webs.main.MyFirstWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:4567/one?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:4567/one?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MYFIRSTWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public MyFirstWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyFirstWebServiceService() {
        super(MYFIRSTWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://main.webs.mao.com/", "MyFirstWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns MyFirstWebService
     */
    @WebEndpoint(name = "MyFirstWebServicePort")
    public MyFirstWebService getMyFirstWebServicePort() {
        return super.getPort(new QName("http://main.webs.mao.com/", "MyFirstWebServicePort"), MyFirstWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyFirstWebService
     */
    @WebEndpoint(name = "MyFirstWebServicePort")
    public MyFirstWebService getMyFirstWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main.webs.mao.com/", "MyFirstWebServicePort"), MyFirstWebService.class, features);
    }

}
